### ISSUE TITLE
[PE-D][Tester A] Constraints for company name

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T09-1/tp#225]
Only alphanumeric chars are allowed for the Company’s name when & - () : are fairly common special chars that companies may have in their names. Eg. Ernst & Young. Users may have to type in a different name to meet the allowed format which may be different from the actual company name

![Screenshot 2024-11-08 at 3.09.42 PM.png](https://raw.githubusercontent.com/Raghava-Chittidi/ped/main/files/7783e655-938a-43f3-868b-49ca37217ea6.png)Screenshot 2024-11-08 at 3.09.42 PM

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Raghava-Chittidi/ped#11

**Comment by blanklogic** [comment]
Since this has been pointed out by one of our testers during PE-D, I believe we can expedite the change of regex from strictly alphanumeric to alphanumeric + symbols by changing the Name class. This would in turn allow both Companies and Applications to have names with special characters such as the previously discussed `UI/UX developer`.
